### ISSUE TITLE
Throws NREs in console on load as of v50 beta

### ISSUE THREAD

**Issue by Re-VelatoR** [Zaggy1024/LC_NutcrackerFixes#2]
As title says. Says failed to patch content.

**Comment by Zaggy1024** [comment]
This is a known issue, I'm considering deprecating this mod, because:

1. v50 has fixed the largest problems with shotgun hit registration, which is why the patches fail now.
2. [Matty's AdditionalNetworking mod](https://github.com/mattymatty97/LTC_AdditionalNetworking) will hopefully fix the desync of the safety and ammo count that this mod contains networking patches for.

The only things that this mod does that I can think of at the moment which will still have an effect in v50 are:
- It decreases the possibility of multiple blobs or enemy corpses in your area causing a non-registering shot. This is very unlikely in practice.
- It prevents blobs from making a bunch of angry sounds at once, which can be annoying but probably doesn't affect performance too much.

Whatever the case may be, I won't be deprecating or updating it for v50 until that version of the game is considered stable by Zeekers.

**Comment by Zaggy1024** [comment]
The mod has been deprecated on the store for a while, but I forgot to come back and close this.
